name: Release action

on:
  push:
    tags:
        - 'v*.*.*'

  workflow_dispatch:
    inputs:
      tag-name:
        description: Release tag
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: ./create-release
        with:
          tag-name: ${{ github.event_name != 'workflow_dispatch' && github.ref_name || inputs.tag-name }}
