name: Release action

on:
  push:
    tags:
        - 'v*.*.*'

  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          name: ${{ env.TAG_NAME }}
        env:
          TAG_NAME: ${{ github.event_name == 'push' && github.ref_name || inputs.tag_name }}
